baseURL = "https://akansharmn.github.io/"
languageCode = "en-us"
title = "Eddie Webb"
theme = "resume"
publishDir ="."

[params]
    firstName = "Akansha"
    lastName = "Raman"
    address = "Jersey City, New Jersey, 07302"
    phone = "1-201-695-4744"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/dp.jpeg"
    email = "akansha.raman23@gmail.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/akansha-raman-88b24479/"


[[params.handles]]
    name = "GitHub"
    link = "https://akansharmn.github.io"


